applications:
  WebApp:
    applicationName: WebApp
    deploymentTrain:
      - name: Staging
        autoDeploy: true
        deploymentFiles: []
        version: 1
      - name: Production
        autoDeploy: false
        deploymentFiles: []
        version: 1
    version: 1
version: 1
